/********************************/
/*                              */
/* This file is created         */
/* automatically during         */
/* compilation. Do not edit.    */
/* See perl script              */
/* "varparser.pl" for details   */
/*                              */
/********************************/
real	DT;
real	SIGMA0;
int	NINTERM;
int	NTOT;
char	OUTPUTDIR[512];
char	OPENINNERBOUNDARY[512];
char	ADVLABEL[512];
char	TRANSPORT[512];
char	PLANETCONFIG[512];
real	MASSTAPER;
char	GRIDSPACING[512];
int	NRAD;
int	NSEC;
real	RMIN;
real	RMAX;
real	THICKNESSSMOOTHING;
real	ROCHESMOOTHING;
real	ASPECTRATIO;
real	VISCOSITY;
real	ALPHAVISCOSITY;
real	SIGMASLOPE;
real	RELEASERADIUS;
real	RELEASEDATE;
real	OMEGAFRAME;
char	DISK[512];
char	FRAME[512];
char	OUTERSOURCEMASS[512];
char	WRITEDENSITY[512];
char	WRITEVELOCITY[512];
char	WRITEENERGY[512];
char	WRITETEMPERATURE[512];
char	WRITEDIVV[512];
char	WRITEQPLUS[512];
char	INDIRECTTERM[512];
char	EXCLUDEHILL[512];
real	IMPOSEDDISKDRIFT;
real	FLARINGINDEX;
real	ECCENTRICITY;
real	CAVITYRADIUS;
real	CAVITYRATIO;
real	CAVITYWIDTH;
real	TRANSITIONRADIUS;
real	TRANSITIONRATIO;
real	TRANSITIONWIDTH;
real	LAMBDADOUBLING;
char	SELFGRAVITY[512];
char	CICPLANET[512];
char	FORCEDCIRCULAR[512];
char	ZMPLUS[512];
char	ADIABATIC[512];
real	ADIABATICINDEX;
char	COOLING[512];
real	COOLINGTIME0;
real	TRACEWIDTH;
real	OUTTRUNC;
real	INTRUNC;
real	FIN;
real	SGSMOOTH;
real	DENFLOOR;
real	FOUT;
real	PLANET_ON;
real	PERTMIN;
real	PERTMAX;
real	PERTTIME;
real	DAMPRATEIN;
real	DAMPRATEOUT;
real	DAMPRADOUT;
real	DAMPRADIN;
real	QOUT;
real	SIGSCALE;
real	TSCALE;
real	HPLANET;
real	EOSN;
real	HCUT;
real	RDEAD1;
real	RDEAD2;
real	DNU;
real	ANU;
real	RONE;
int	PERT_MMIN;
int	PERT_MMAX;
