# Makefile for the relativistic MHD Module 

VPATH += $(SRC)/RMHD
OBJ   +=  eigenv.o eos.o energy_solve.o entropy_solve.o fluxes.o \
          mappers.o pressure_fix.o tvdlf.o \
          hll_speed.o hll.o hllc.o hlld.o quartic.o rhs.o \
          set_solver.o source.o vel_limiter.o 
 

